### ISSUE TITLE
xamarin forms + msal + intunes sdk

### ISSUE THREAD

**Issue by viveknegi51288** [rzdebskiy/IntuneSDK_XamarinForms_Sample#1]
Hi @rzdebskiy 

I have created an application with msal library to authenticate the user and getting mfa token from there.,now i have to include intunes sdk into my app. Can you please any sample application.

**Comment by viveknegi51288** [comment]
@rzdebskiy  In your sample you are enrolling in intune from IOS , could you tell me how to register in android ?

**Comment by rzdebskiy** [comment]
> @rzdebskiy In your sample you are enrolling in intune from IOS , could you tell me how to register in android ?

Hi @viveknegi51288 
Actually enrolling process is pretty similar - you install Intune Company Portal App to Android device  https://play.google.com/store/apps/details?id=com.microsoft.windowsintune.companyportal&hl=en and follow similar steps - https://docs.microsoft.com/en-us/mem/intune/user-help/enroll-device-android-company-portal

**Comment by rzdebskiy** [comment]
> Hi @rzdebskiy
> 
> I have created an application with msal library to authenticate the user and getting mfa token from there.,now i have to include intunes sdk into my app. Can you please any sample application.

@viveknegi51288 This repo (https://github.com/rzdebskiy/IntuneSDK_XamarinForms_Sample) has a sample app both for Android and iOS - does it work for you?
